<footer>
      <section class="container">
        <section class="footer-content">
          
          <nav class="social-icons" aria-label="Social media links">
            <a href="mailto:105098518@student.swin.edu.au"><i class="fas fa-envelope"></i></i
            ></a>
            <a href="#" aria-label="Twitter"
              ><i class="fab fa-twitter" ></i
            ></a>
            <a href="#" aria-label="LinkedIn"
              ><i class="fab fa-linkedin" ></i
            ></a>
            <a href="#" aria-label="Instagram"
              ><i class="fab fa-instagram" ></i
            ></a>
          </nav>
          <p>&copy; 2023 jobLock. All rights reserved.</p>
        </section>
      </section>
    </footer>
  </body>
</html>
